{
    "openapi": "3.0.0",
    "info": {
        "title": "Projeto final CRUD API",
        "version": "1.0.0",
        "descripition": "Documentação da API Projeto final CRUD Backend Para diciplina de Topicos Especiais Em computação",

        "contact": {
            "name": "Github Repository",
            "email": "",
            "url": "https://github.com/MatheusGSantos/UFPB-TEES"
        }
    },

    "servers": [
        {
            "url": "https://app-projeto-final-backend.herokuapp.com",
            "descripiton": "Deployed server"
        },
        {
            "url": "http://localhost:3333",
            "descripiton": "Servidor local"
        }
    ],

    "paths": {
        "/users": {
            "get": {
                "summary": "Lista todos os usuários",
                "description": "Retorna a lista de todos os usuários em um array ou um unico se for fornecido email na query",
                "tags": ["users"],

                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "description": "email do usuario",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "simple"
                    }
                ],

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/userResponse"
                                    }
                                }
                            }
                        }
                    },

                    "405": {
                        "description": "Usuario nao encontrado por email",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },

            "post": {
                "summary": "Cadastra um novo usuario",
                "description": "Cadastra um novo usuario se ainda não existir, retorna um error se o ususario já existe",
                "tags": ["users"],

                "parameters": [
                    {
                        "name": "name",
                        "in": "body",
                        "description": "Name do usuario",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    },
                    {
                        "name": "email",
                        "in": "body",
                        "description": "Email do usuario",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    },
                    {
                        "name": "password",
                        "in": "body",
                        "description": "Senha do usuario",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    }
                ],

                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/newUser"
                            },
                            "example": {
                                "name": "Matheus Examplo",
                                "email": "usuario@existente.com",
                                "senha": "senhaValida"
                            }
                        }
                    }
                },

                "responses": {
                    "200": {
                        "description": "Usuario cadastrado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/userResponse"
                                },
                                "example": {
                                    "id": "b36a11bc-4d32-43a4-9325-47b1b76ffb1d",
                                    "name": "Example User",
                                    "email": "example@gmail.com",
                                    "created_at": "2022-06-24T21:30:10.744Z",
                                    "updated_at": "2022-06-24T21:30:10.744Z"
                                }
                            }
                        }
                    },

                    "409": {
                        "description": "User already exists",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mensage"
                                },
                                "example": {
                                    "error": "409",
                                    "message": "User already exists"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/sessions": {
            "post": {
                "summary": "Autentição no app para alterar e deletar um usuario existente",
                "description": "A atuenticação dura 1 dia, e feita araves de JWT dando permissão ao usuario logado a Deletar e atualizar usuarios ja existentes",
                "tags": ["authentication"],

                "parameters": [
                    {
                        "email": "email",
                        "in": "body",
                        "description": "Email do usuario ja cadastrado",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    },
                    {
                        "password": "password",
                        "in": "body",
                        "description": "Senha do usuario ja cadastrado",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    }
                ],

                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/authenticatedUser"
                            },
                            "example": {
                                "email": "usuario@existente.com",
                                "senha": "senhaValida"
                            }
                        }
                    }
                },

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/userAuthenticatedSucessful"
                                },
                                "example": {
                                    "user": {
                                        "id": "b36a11bc-4d32-43a4-9325-47b1b76ffb1d",
                                        "name": "exmaple User",
                                        "email": "example@gmail.com",
                                        "created_at": "2022-06-24T21:30:10.744Z",
                                        "updated_at": "2022-06-24T21:30:10.744Z"
                                    },
                                    "token": "token.jwt.auth"
                                }
                            }
                        }
                    },

                    "404": {
                        "description": "Password does not match or User not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mensage"
                                },
                                "examples": {
                                    "userNotFound": {
                                        "summary": "User not found",
                                        "value": {
                                            "mensage": "user not found",
                                            "error": "404"
                                        }
                                    },
                                    "passwordDosentMatch": {
                                        "summary": "password does not match",
                                        "value": {
                                            "mensage": "password does not match",
                                            "error": "404"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/users/{id}": {
            "patch": {
                "summary": "Atualiza um usuario",
                "description": "Atualiza um usuario ja existente, para atualizar e preciso esta autenticado",
                "tags": ["auth routes"],
                "security": [{ "bearerAuth": [] }],

                "parameters": [
                    {
                        "id": "id",
                        "in": "query",
                        "description": "id do usuario ja cadastrado",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    },
                    {
                        "email": "email",
                        "in": "body",
                        "description": "email do usuario ja cadastrado",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    },
                    {
                        "name": "name",
                        "in": "body",
                        "description": "Nome do usuario ja cadastrado",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    }
                ],

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/updatedUser"
                                },
                                "example": {
                                    "user": {
                                        "id": "b36a11bc-4d32-43a4-9325-47b1b76ffb1d",
                                        "name": "exmaple User atualizado",
                                        "email": "exampleAtualizado@gmail.com",
                                        "created_at": "2022-06-24T21:30:10.744Z",
                                        "updated_at": "2022-06-24T21:30:10.744Z"
                                    }
                                }
                            }
                        }
                    },

                    "400": {
                        "description": "Invalid Id or User not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mensage"
                                },
                                "examples": {
                                    "userNotFound": {
                                        "summary": "User not found",
                                        "value": {
                                            "mensage": "User not found",
                                            "error": "400"
                                        }
                                    },
                                    "invalidID": {
                                        "summary": "Invalid ID",
                                        "value": {
                                            "mensage": "Invalid ID",
                                            "error": "400"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },

            "delete": {
                "summary": "Delete um usuario",
                "description": "Delete um usuario ja existente, para deletar e preciso esta autenticado",
                "tags": ["auth routes"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "id": "id",
                        "in": "query",
                        "description": "ID do usuario ja cadastrado",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },

                        "style": "simple"
                    }
                ],

                "responses": {
                    "204": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mensage"
                                },
                                "example": {
                                    "mensage": "204"
                                }
                            }
                        }
                    },

                    "400": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mensage"
                                },
                                "examples": {
                                    "userNotFound": {
                                        "summary": "User not found",
                                        "value": {
                                            "mensage": "User not found",
                                            "error": "400"
                                        }
                                    },
                                    "invalidID": {
                                        "summary": "Invalid ID",
                                        "value": {
                                            "mensage": "Invalid ID",
                                            "error": "400"
                                        }
                                    }
                                }
                            }
                        }
                    },

                    "404": {
                        "description": "You can't delete your own account",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mensage"
                                },
                                "example": {
                                    "mensage": "You can't delete your own account",
                                    "error": "404"
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    "components": {
        "schemas": {
            "userResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    },
                    "token": {
                        "type": "string"
                    }
                }
            },
            "newUser": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "mensage": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    },
                    "error": {
                        "type": "string"
                    }
                }
            },
            "authenticatedUser": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "userAuthenticatedSucessful": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    },

                    "token": {
                        "type": "string"
                    }
                }
            },

            "updatedUser": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
